version: '3.8'

services:
  spring-boot:
    build:
      context: .
      dockerfile: .docker/spring-boot/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-refactorian}
      DB_USERNAME: ${DB_USERNAME:-refactorian}
      DB_PASSWORD: ${DB_PASSWORD:-refactorian}
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - spring-boot
    restart: always

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-refactorian}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-refactorian}
      POSTGRES_DB: ${DB_DATABASE:-refactorian}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api-docs/openapi.yaml
    volumes:
      - ./api-docs:/api-docs

  mail:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: always

volumes:
  pgdata:
  redisdata:
